version: "3.8"

services:
  mongodb-server:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb
  redis-server:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data/redis
  api-server:
    environment:
      - REDIS_URL=$REDIS_URL
      - DB_CONNECTION=$DB_CONNECTION
    build:
      context: ./server
    ports:
      - "5000:5000"
  tree-client:
    environment:
      - REACT_APP_API_URL=http://api-server:5000/api
    build:
      context: ./client
    ports:
      - "3000:80"

volumes:
  db-data:
  mongo-config:
  redis-data:

# docker-compose -f ./docker-compose.prod.yml --env-file ./server/.env up
