version: "3.8"

services:
  mongodb-server:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb
  redis-server:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data/redis

volumes:
  db-data:
  mongo-config:
  redis-data:
